name: Gradle Build
run-name: ${{ github.actor }} pushed a new commit
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1
      - name: Clone timecard-lib
        uses: actions/checkout@v3
        with:
          repository: Stephen-Hamilton-C/timecard-lib
      - name: Publish timecard-lib to Local Maven Repo
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal
      - name: Clone current commit
        uses: actions/checkout@v3
      - name: Execute Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
